---
- name: install certbot
  apt:
    name: certbot
    state: present
  become: true

- name: check if cert is already present
  stat:
    path: /etc/letsencrypt/live
  register: stat_result

- debug:
    msg: letsencrypt.host {{letsencrypt.host}}

# - name: get initial cert
#   command: "certbot certonly --standalone -d '{{letsencrypt.host}}'"
#   become: true
  # when: not stat_result.stat.exists

  #
  #- name: certbot cron job
  #  cron:
  #    name: renew SSL cert if needed
  #    minute: 15
  #    hour: 3
  #    job: >
  #      certbot renew --noninteractive
  #      --pre-hook "{{ certbot_pre_hook }}"
  #      --post-hook "{{ certbot_post_hook }}"
  #    state: present
  #  become: true
