---
- debug:
    msg: letsencrypt.host {{letsencrypt}}

- name: install certbot
  apt:
    name: ['certbot', 'python-certbot-nginx']
    state: present
  become: true

- name: check if cert is already present
  stat:
    path: /etc/letsencrypt/live
  register: stat_result

# nginx installer doesnt work, seems like it looks for server_name matching the
# domain, doenst find server_name=_
- name: get cert
  command: >
    certbot run
    --non-interactive
    --agree-tos
    --email {{letsencrypt.email}}
    --authenticator webroot
    --webroot-path {{letsencrypt.web_root}}
    --installer nginx
    --domain {{letsencrypt.host_name}}
  become: true
  when: not stat_result.stat.exists

  #
  #- name: certbot cron job
  #  cron:
  #    name: renew SSL cert if needed
  #    minute: 15
  #    hour: 3
  #    job: >
  #      certbot renew --noninteractive
  #      --pre-hook "{{ certbot_pre_hook }}"
  #      --post-hook "{{ certbot_post_hook }}"
  #    state: present
  #  become: true
