---
# TODO: static ip
# TODO: letsencrypt autorenew
- name: Home assistant
  hosts: all
  vars:
    host_name: home.johnvh.com
    web_root: /srv/www/{{host_name}}
    ddclient_conf:
      - name: dynamic dns for home.johnvh.com
        protocol: namecheap
        use: web, web=dynamicdns.park-your-domain.com/getip
        server: dynamicdns.park-your-domain.com
        login: johnvh.com
        password: "{{ ddclient_password }}"
        address: home
    nginx:
      web_root: '{{web_root}}'
      web_root_owner: www-data
      web_root_group: www-data
    letsencrypt:
      host_name: '{{host_name}}'
      web_root: '{{web_root}}'
      email: jmvanhorn@gmail.com
  roles:
    # - jpartain89.ddclient
    - nginx
    # - letsencrypt
  tasks:
    - name: install sqlite3
      apt:
        name: sqlite3
        state: present
      become: true
